(load "./fizzbuzz.lisp")
(ql:quickload :prove)

(setf prove:*default-reporter* :tap)
(prove:plan 20)

(prove:is 1 (fizzbuzz 1))
(prove:is 2 (fizzbuzz 2))
(prove:is "Fizz" (fizzbuzz 3))
(prove:is 4 (fizzbuzz 4))
(prove:is "Buzz" (fizzbuzz 5))
(prove:is "Fizz" (fizzbuzz 6))
(prove:is 7 (fizzbuzz 7))
(prove:is 8 (fizzbuzz 8))
(prove:is "Fizz" (fizzbuzz 9))
(prove:is "Buzz" (fizzbuzz 10))
(prove:is 11 (fizzbuzz 11))
(prove:is "Fizz" (fizzbuzz 12))
(prove:is 13 (fizzbuzz 13))
(prove:is 14 (fizzbuzz 14))
(prove:is "FizzBuzz" (fizzbuzz 15))
(prove:is 16 (fizzbuzz 16))
(prove:is 17 (fizzbuzz 17))
(prove:is "Fizz" (fizzbuzz 18))
(prove:is 19 (fizzbuzz 19))
(prove:is "Buzz" (fizzbuzz 20))

(prove:finalize)
(exit)
